name: Publish

on:
  release:
    types: [published]

jobs:
  pypi:
    runs-on: nscloud-ubuntu-24.04-amd64-4x8
    timeout-minutes: 15
    environment: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uv build
      - run: uv publish --trusted-publishing always
